# Generated by Django 5.2.6 on 2025-09-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
    ]
