# Generated by Django 5.2.6 on 2025-09-11 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_deadlines_priorities'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Query Categories',
            },
        ),
        migrations.CreateModel(
            name='QueryPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Query Priorities',
            },
        ),
        migrations.CreateModel(
            name='QueryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Query Statuses',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('query_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('requires_follow_up', models.BooleanField(default=False)),
                ('is_escalated', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_queries', to='portal.stafftbl')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.childinhouseholdtbl')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_queries', to='portal.stafftbl')),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_queries', to='portal.stafftbl')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.farmertbl')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.householdtbl')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.querycategory')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.querypriority')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.querystatus')),
            ],
            options={
                'verbose_name_plural': 'Queries',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='FlaggedIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('flag_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('flag_type', models.CharField(choices=[('data_quality', 'Data Quality Issue'), ('child_labour', 'Child Labour Concern'), ('safety', 'Safety Concern'), ('ethical', 'Ethical Concern'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('reviewed', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_issues', to='portal.stafftbl')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_issues', to='portal.stafftbl')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='portal.query')),
            ],
            options={
                'verbose_name_plural': 'Flagged Issues',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='QueryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('file', models.FileField(upload_to='query_attachments/')),
                ('file_name', models.CharField(max_length=255)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='portal.query')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.stafftbl')),
            ],
            options={
                'verbose_name_plural': 'Query Attachments',
            },
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('escalation_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('escalation_type', models.CharField(choices=[('technical', 'Technical Issue'), ('managerial', 'Managerial Decision'), ('safety', 'Safety Concern'), ('ethical', 'Ethical Issue'), ('other', 'Other')], max_length=20)),
                ('reason', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('escalated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations_made', to='portal.stafftbl')),
                ('escalated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations_received', to='portal.stafftbl')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='portal.query')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.querypriority')),
            ],
            options={
                'verbose_name_plural': 'Escalations',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='QueryResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('response_text', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='query_responses/')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='portal.query')),
                ('responded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.stafftbl')),
            ],
            options={
                'verbose_name_plural': 'Query Responses',
                'ordering': ['created_date'],
            },
        ),
    ]
