# Generated by Django 5.2.6 on 2025-09-11 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_querycategory_querypriority_querystatus_query_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('risk_level', models.CharField(choices=[('no_risk', 'No Risk'), ('light_risk', 'Light Task Risk'), ('heavy_risk', 'Heavy Task Risk'), ('both_risk', 'Both Light and Heavy Task Risk')], default='no_risk', max_length=20)),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='portal.childinhouseholdtbl')),
            ],
            options={
                'verbose_name_plural': 'Risk Assessments',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='LightTaskRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('task_name', models.CharField(max_length=100)),
                ('risk_detected_date', models.DateTimeField(auto_now_add=True)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_supervised', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('child_age', models.IntegerField()),
                ('meets_criteria', models.BooleanField(default=False)),
                ('criteria_details', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.lighttasktbl')),
                ('risk_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='light_task_risks', to='portal.riskassessment')),
            ],
            options={
                'verbose_name_plural': 'Light Task Risks',
            },
        ),
        migrations.CreateModel(
            name='HeavyTaskRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('task_name', models.CharField(max_length=100)),
                ('risk_detected_date', models.DateTimeField(auto_now_add=True)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.heavytasktbl')),
                ('risk_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heavy_task_risks', to='portal.riskassessment')),
            ],
            options={
                'verbose_name_plural': 'Heavy Task Risks',
            },
        ),
        migrations.CreateModel(
            name='RiskAssessmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('previous_risk_level', models.CharField(max_length=20)),
                ('new_risk_level', models.CharField(max_length=20)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.stafftbl')),
                ('risk_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='portal.riskassessment')),
            ],
            options={
                'verbose_name_plural': 'Risk Assessment History',
                'ordering': ['-change_date'],
            },
        ),
    ]
