# Generated by Django 5.2.6 on 2025-09-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_riskassessment_lighttaskrisk_heavytaskrisk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heavytasktbl',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='heavytasktbl',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lighttasktbl',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lighttasktbl',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
