# Generated by Django 5.2.6 on 2025-09-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_heavytasktbl_create_at_heavytasktbl_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heavytasktbl',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='lighttasktbl',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
