# Generated by Django 5.2.6 on 2025-09-12 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auditstatus_audittype_auditcheck_auditattachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rule_type', models.CharField(choices=[('completeness', 'Data Completeness'), ('consistency', 'Data Consistency'), ('range', 'Value Range Check'), ('logic', 'Logical Validation'), ('cross_field', 'Cross-field Validation')], max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('validation_expression', models.TextField(help_text='Python expression or validation logic')),
                ('error_message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Validation Rules',
            },
        ),
        migrations.CreateModel(
            name='HighRiskCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('risk_category', models.CharField(choices=[('data_quality', 'Data Quality Issues'), ('child_labor', 'Child Labor Indicators'), ('forced_labor', 'Forced Labor Indicators'), ('safety', 'Safety Concerns'), ('ethical', 'Ethical Concerns')], max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('description', models.TextField()),
                ('indicators', models.TextField(help_text='Specific indicators that triggered this risk case')),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='open', max_length=20)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.stafftbl')),
                ('household_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_risk_cases', to='portal.householdtbl')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_cases', to='portal.stafftbl')),
            ],
            options={
                'verbose_name_plural': 'High Risk Cases',
            },
        ),
        migrations.CreateModel(
            name='SurveyApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_correction', 'Requires Correction')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('correction_required', models.BooleanField(default=False)),
                ('correction_details', models.TextField(blank=True, null=True)),
                ('correction_deadline', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_surveys', to='portal.stafftbl')),
                ('household_survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='portal.householdtbl')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_surveys', to='portal.stafftbl')),
            ],
            options={
                'verbose_name_plural': 'Survey Approvals',
            },
        ),
        migrations.CreateModel(
            name='SurveyValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Validation'), ('passed', 'Validation Passed'), ('failed', 'Validation Failed'), ('requires_review', 'Requires Manual Review')], default='pending', max_length=20)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('household_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='portal.householdtbl')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.stafftbl')),
                ('validation_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.validationrule')),
            ],
            options={
                'verbose_name_plural': 'Survey Validation Results',
                'unique_together': {('household_survey', 'validation_rule')},
            },
        ),
    ]
