# Generated by Django 5.2.6 on 2025-09-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_validationrule_highriskcase_surveyapproval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdtbl',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householdtbl',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
