# Generated by Django 5.2.6 on 2025-09-13 20:58

import portal.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_householdtbl_latitude_householdtbl_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adulthouseholdmember',
            name='gender',
            field=models.CharField(choices=[('Boy', 'Boy'), ('Girl', 'Girl')], max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='childinhouseholdtbl',
            name='child_identifier',
            field=models.PositiveSmallIntegerField(help_text="Enter the number attached to the child's name in the cover (must be less than 20).", validators=[portal.validators.FlexibleIntegerValidator(1), portal.validators.FlexibleIntegerValidator(19)], verbose_name='Child identifier'),
        ),
        migrations.AlterField(
            model_name='childinhouseholdtbl',
            name='child_year_birth',
            field=models.IntegerField(help_text='The year must be between 2007 and 2020 (child must be between 5 and 17 years old).', validators=[portal.validators.FlexibleIntegerValidator(2007), portal.validators.FlexibleIntegerValidator(2020)], verbose_name='Year of Birth of the Child'),
        ),
    ]
