# Generated by Django 5.2.6 on 2025-09-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_adulthouseholdmember_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childinhouseholdtbl',
            name='child_identifier',
            field=models.PositiveSmallIntegerField(help_text="Enter the number attached to the child's name in the cover (must be less than 20).", verbose_name='Child identifier'),
        ),
        migrations.AlterField(
            model_name='childinhouseholdtbl',
            name='child_year_birth',
            field=models.IntegerField(help_text='The year must be between 2007 and 2020 (child must be between 5 and 17 years old).', verbose_name='Year of Birth of the Child'),
        ),
    ]
