# Generated by Django 5.2.6 on 2025-09-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_alter_childinhouseholdtbl_calculation_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childinhouseholdtbl',
            name='sch_going_times',
            field=models.CharField(blank=True, choices=[('once', 'Once'), ('twice', 'Twice'), ('thrice', 'Thrice'), ('four_times', 'Four times'), ('five_times', 'Five times')], help_text='How many times does the child go to school in a week?', max_length=10, null=True),
        ),
    ]
