# Generated by Django 5.2.6 on 2025-09-10 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Deadline Types',
            },
        ),
        migrations.CreateModel(
            name='PriorityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Priority Levels',
            },
        ),
        migrations.RenameField(
            model_name='districttbl',
            old_name='region',
            new_name='regionTbl_foreignkey',
        ),
        migrations.CreateModel(
            name='DeadlineAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('staff_type', models.CharField(choices=[('Staff', 'Staff'), ('Enumerator', 'Enumerator')], default='Staff', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Overdue', 'Overdue')], default='Pending', max_length=20)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_deadlines', to='portal.stafftbl')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_assignments', to='portal.stafftbl')),
                ('deadline_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.deadlinetype')),
                ('priority_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.prioritylevel')),
            ],
            options={
                'verbose_name_plural': 'Deadline Assignments',
                'ordering': ['-created_date'],
            },
        ),
    ]
